name: Testing pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install
        working-directory: dungeon-generator

      - name: Run Tests
        run: npm run test:run
        working-directory: dungeon-generator